### ISSUE TITLE
Question regarding keyframe animations

### ISSUE THREAD

**Issue by revolter** [kharrison/Property-Animators#1]
Isn't it wrong to call old style animation API inside the new API?

https://github.com/kharrison/Property-Animators/blob/e459e540d31127dabc95389b84773f929634fd6a/PropertyAnimators.playground/Contents.swift#L271-L287

Is `fractionComplete` working in this case?

**Comment by kharrison** [comment]
Opps this is an old issue that I missed. I'm no expert on interruptable animations so I would be happy to learn more.

Do you have a reference for where Apple say it's wrong or not working? They show this approach of using key frame animations with a property animator in WWDC 2016 Session 216 - Advances in UIKit Animations and Transitions.

It's covered in the last few minutes see [WWDC 2016 Session 216](https://developer.apple.com/videos/play/wwdc2016-216/?time=2650).

**Comment by revolter** [comment]
Oh, maybe I was wrong then.
